name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build with CMake
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest]
    steps:
    - uses: actions/checkout@v4
    - name: Setup CCache
      uses: hendrikmuhs/ccache-action@v1.2
      with:
        key: ${{ github.job }}-${{ runner.os }}
    - uses: extractions/setup-just@v3
    - name: Setup VCPKG
      uses: lukka/run-vcpkg@v11
      env:
        VCPKG_BINARY_SOURCES: default,rw
    # Cache vcpkg binary sources.
    # Adapted from https://github.com/lukka/run-vcpkg/issues/251
    - name: Setup VCPKG Cache
      uses: actions/cache@v4
      with:
        path: ${{ env.VCPKG_DEFAULT_BINARY_CACHE }}
        key: ${{ runner.os }}-vcpkg-binary-cache-${{ hashFiles('vcpkg*.json') }}
        restore-keys: |
            ${{ runner.os }}-vcpkg-binary-cache-
    - name: Pull Dependencies
      run: just sync
    - name: Generate Build Directory
      run: just setup release
    - name: Build with CMake
      run: just build release
